extern int __sched_cpucount (size_t __setsize, const cpu_set_t *__setp) ;
extern cpu_set_t *__sched_cpualloc (size_t __count) ;
extern void __sched_cpufree (cpu_set_t *__set) ;
extern int sched_setparam (__pid_t __pid, const struct sched_param *__param) ;
extern int sched_getparam (__pid_t __pid, struct sched_param *__param) ;
extern int sched_setscheduler (__pid_t __pid, int __policy, const struct sched_param *__param) ;
extern int sched_getscheduler (__pid_t __pid) ;
extern int sched_yield (void) ;
extern int sched_get_priority_max (int __algorithm) ;
extern int sched_get_priority_min (int __algorithm) ;
extern int sched_rr_get_interval (__pid_t __pid, struct timespec *__t) ;
extern clock_t clock (void) ;
extern time_t time (time_t *__timer) ;
extern double difftime (time_t __time1, time_t __time0) ;
extern time_t mktime (struct tm *__tp) ;
extern size_t strftime (char *__restrict __s, size_t __maxsize, const char *__restrict __format, const struct tm *__restrict __tp) ;
extern size_t strftime_l (char *__restrict __s, size_t __maxsize, const char *__restrict __format, const struct tm *__restrict __tp, locale_t __loc) ;
extern struct tm *gmtime (const time_t *__timer) ;
extern struct tm *localtime (const time_t *__timer) ;
extern struct tm *gmtime_r (const time_t *__restrict __timer, struct tm *__restrict __tp) ;
extern struct tm *localtime_r (const time_t *__restrict __timer, struct tm *__restrict __tp) ;
extern char *asctime (const struct tm *__tp) ;
extern char *ctime (const time_t *__timer) ;
extern char *asctime_r (const struct tm *__restrict __tp, char *__restrict __buf) ;
extern char *ctime_r (const time_t *__restrict __timer, char *__restrict __buf) ;
extern char *__tzname[2];
extern int __daylight;
extern long int __timezone;
extern char *tzname[2];
extern void tzset (void) ;
extern int daylight;
extern long int timezone;
extern int stime (const time_t *__when) ;
extern time_t timegm (struct tm *__tp) ;
extern time_t timelocal (struct tm *__tp) ;
extern int dysize (int __year) ;
extern int nanosleep (const struct timespec *__requested_time, struct timespec *__remaining);
extern int clock_getres (clockid_t __clock_id, struct timespec *__res) ;
extern int clock_gettime (clockid_t __clock_id, struct timespec *__tp) ;
extern int clock_settime (clockid_t __clock_id, const struct timespec *__tp) ;
extern int clock_nanosleep (clockid_t __clock_id, int __flags, const struct timespec *__req, struct timespec *__rem);
extern int clock_getcpuclockid (pid_t __pid, clockid_t *__clock_id) ;
extern int timer_create (clockid_t __clock_id, struct sigevent *__restrict __evp, timer_t *__restrict __timerid) ;
extern int timer_delete (timer_t __timerid) ;
extern int timer_settime (timer_t __timerid, int __flags, const struct itimerspec *__restrict __value, struct itimerspec *__restrict __ovalue) ;
extern int timer_gettime (timer_t __timerid, struct itimerspec *__value) ;
extern int timer_getoverrun (timer_t __timerid) ;
extern int timespec_get (struct timespec *__ts, int __base) ;
extern int pthread_create (pthread_t *__restrict __newthread, const pthread_attr_t *__restrict __attr, void *(*__start_routine) (void *), void *__restrict __arg) ;
extern void pthread_exit (void *__retval) ;
extern int pthread_join (pthread_t __th, void **__thread_return);
extern int pthread_detach (pthread_t __th) ;
extern pthread_t pthread_self (void) ;
extern int pthread_equal (pthread_t __thread1, pthread_t __thread2) ;
extern int pthread_attr_init (pthread_attr_t *__attr) ;
extern int pthread_attr_destroy (pthread_attr_t *__attr) ;
extern int pthread_attr_getdetachstate (const pthread_attr_t *__attr, int *__detachstate) ;
extern int pthread_attr_setdetachstate (pthread_attr_t *__attr, int __detachstate) ;
extern int pthread_attr_getguardsize (const pthread_attr_t *__attr, size_t *__guardsize) ;
extern int pthread_attr_setguardsize (pthread_attr_t *__attr, size_t __guardsize) ;
extern int pthread_attr_getschedparam (const pthread_attr_t *__restrict __attr, struct sched_param *__restrict __param) ;
extern int pthread_attr_setschedparam (pthread_attr_t *__restrict __attr, const struct sched_param *__restrict __param) ;
extern int pthread_attr_getschedpolicy (const pthread_attr_t *__restrict __attr, int *__restrict __policy) ;
extern int pthread_attr_setschedpolicy (pthread_attr_t *__attr, int __policy) ;
extern int pthread_attr_getinheritsched (const pthread_attr_t *__restrict __attr, int *__restrict __inherit) ;
extern int pthread_attr_setinheritsched (pthread_attr_t *__attr, int __inherit) ;
extern int pthread_attr_getscope (const pthread_attr_t *__restrict __attr, int *__restrict __scope) ;
extern int pthread_attr_setscope (pthread_attr_t *__attr, int __scope) ;
extern int pthread_attr_getstackaddr (const pthread_attr_t *__restrict __attr, void **__restrict __stackaddr) ;
extern int pthread_attr_setstackaddr (pthread_attr_t *__attr, void *__stackaddr) ;
extern int pthread_attr_getstacksize (const pthread_attr_t *__restrict __attr, size_t *__restrict __stacksize) ;
extern int pthread_attr_setstacksize (pthread_attr_t *__attr, size_t __stacksize) ;
extern int pthread_attr_getstack (const pthread_attr_t *__restrict __attr, void **__restrict __stackaddr, size_t *__restrict __stacksize) ;
extern int pthread_attr_setstack (pthread_attr_t *__attr, void *__stackaddr, size_t __stacksize) ;
extern int pthread_setschedparam (pthread_t __target_thread, int __policy, const struct sched_param *__param) ;
extern int pthread_getschedparam (pthread_t __target_thread, int *__restrict __policy, struct sched_param *__restrict __param) ;
extern int pthread_setschedprio (pthread_t __target_thread, int __prio) ;
extern int pthread_once (pthread_once_t *__once_control, void (*__init_routine) (void)) ;
extern int pthread_setcancelstate (int __state, int *__oldstate);
extern int pthread_setcanceltype (int __type, int *__oldtype);
extern int pthread_cancel (pthread_t __th);
extern void pthread_testcancel (void);
extern void __pthread_register_cancel (__pthread_unwind_buf_t *__buf) ;
extern void __pthread_unregister_cancel (__pthread_unwind_buf_t *__buf) ;
extern void __pthread_unwind_next (__pthread_unwind_buf_t *__buf) ;
extern int __sigsetjmp (struct __jmp_buf_tag *__env, int __savemask) ;
extern int pthread_mutex_init (pthread_mutex_t *__mutex, const pthread_mutexattr_t *__mutexattr) ;
extern int pthread_mutex_destroy (pthread_mutex_t *__mutex) ;
extern int pthread_mutex_trylock (pthread_mutex_t *__mutex) ;
extern int pthread_mutex_lock (pthread_mutex_t *__mutex) ;
extern int pthread_mutex_timedlock (pthread_mutex_t *__restrict __mutex, const struct timespec *__restrict __abstime) ;
extern int pthread_mutex_unlock (pthread_mutex_t *__mutex) ;
extern int pthread_mutex_getprioceiling (const pthread_mutex_t * __restrict __mutex, int *__restrict __prioceiling) ;
extern int pthread_mutex_setprioceiling (pthread_mutex_t *__restrict __mutex, int __prioceiling, int *__restrict __old_ceiling) ;
extern int pthread_mutex_consistent (pthread_mutex_t *__mutex) ;
extern int pthread_mutexattr_init (pthread_mutexattr_t *__attr) ;
extern int pthread_mutexattr_destroy (pthread_mutexattr_t *__attr) ;
extern int pthread_mutexattr_getpshared (const pthread_mutexattr_t * __restrict __attr, int *__restrict __pshared) ;
extern int pthread_mutexattr_setpshared (pthread_mutexattr_t *__attr, int __pshared) ;
extern int pthread_mutexattr_gettype (const pthread_mutexattr_t *__restrict __attr, int *__restrict __kind) ;
extern int pthread_mutexattr_settype (pthread_mutexattr_t *__attr, int __kind) ;
extern int pthread_mutexattr_getprotocol (const pthread_mutexattr_t * __restrict __attr, int *__restrict __protocol) ;
extern int pthread_mutexattr_setprotocol (pthread_mutexattr_t *__attr, int __protocol) ;
extern int pthread_mutexattr_getprioceiling (const pthread_mutexattr_t * __restrict __attr, int *__restrict __prioceiling) ;
extern int pthread_mutexattr_setprioceiling (pthread_mutexattr_t *__attr, int __prioceiling) ;
extern int pthread_mutexattr_getrobust (const pthread_mutexattr_t *__attr, int *__robustness) ;
extern int pthread_mutexattr_setrobust (pthread_mutexattr_t *__attr, int __robustness) ;
extern int pthread_rwlock_init (pthread_rwlock_t *__restrict __rwlock, const pthread_rwlockattr_t *__restrict __attr) ;
extern int pthread_rwlock_destroy (pthread_rwlock_t *__rwlock) ;
extern int pthread_rwlock_rdlock (pthread_rwlock_t *__rwlock) ;
extern int pthread_rwlock_tryrdlock (pthread_rwlock_t *__rwlock) ;
extern int pthread_rwlock_timedrdlock (pthread_rwlock_t *__restrict __rwlock, const struct timespec *__restrict __abstime) ;
extern int pthread_rwlock_wrlock (pthread_rwlock_t *__rwlock) ;
extern int pthread_rwlock_trywrlock (pthread_rwlock_t *__rwlock) ;
extern int pthread_rwlock_timedwrlock (pthread_rwlock_t *__restrict __rwlock, const struct timespec *__restrict __abstime) ;
extern int pthread_rwlock_unlock (pthread_rwlock_t *__rwlock) ;
extern int pthread_rwlockattr_init (pthread_rwlockattr_t *__attr) ;
extern int pthread_rwlockattr_destroy (pthread_rwlockattr_t *__attr) ;
extern int pthread_rwlockattr_getpshared (const pthread_rwlockattr_t * __restrict __attr, int *__restrict __pshared) ;
extern int pthread_rwlockattr_setpshared (pthread_rwlockattr_t *__attr, int __pshared) ;
extern int pthread_rwlockattr_getkind_np (const pthread_rwlockattr_t * __restrict __attr, int *__restrict __pref) ;
extern int pthread_rwlockattr_setkind_np (pthread_rwlockattr_t *__attr, int __pref) ;
extern int pthread_cond_init (pthread_cond_t *__restrict __cond, const pthread_condattr_t *__restrict __cond_attr) ;
extern int pthread_cond_destroy (pthread_cond_t *__cond) ;
extern int pthread_cond_signal (pthread_cond_t *__cond) ;
extern int pthread_cond_broadcast (pthread_cond_t *__cond) ;
extern int pthread_cond_wait (pthread_cond_t *__restrict __cond, pthread_mutex_t *__restrict __mutex) ;
extern int pthread_cond_timedwait (pthread_cond_t *__restrict __cond, pthread_mutex_t *__restrict __mutex, const struct timespec *__restrict __abstime) ;
extern int pthread_condattr_init (pthread_condattr_t *__attr) ;
extern int pthread_condattr_destroy (pthread_condattr_t *__attr) ;
extern int pthread_condattr_getpshared (const pthread_condattr_t * __restrict __attr, int *__restrict __pshared) ;
extern int pthread_condattr_setpshared (pthread_condattr_t *__attr, int __pshared) ;
extern int pthread_condattr_getclock (const pthread_condattr_t * __restrict __attr, __clockid_t *__restrict __clock_id) ;
extern int pthread_condattr_setclock (pthread_condattr_t *__attr, __clockid_t __clock_id) ;
extern int pthread_spin_init (pthread_spinlock_t *__lock, int __pshared) ;
extern int pthread_spin_destroy (pthread_spinlock_t *__lock) ;
extern int pthread_spin_lock (pthread_spinlock_t *__lock) ;
extern int pthread_spin_trylock (pthread_spinlock_t *__lock) ;
extern int pthread_spin_unlock (pthread_spinlock_t *__lock) ;
extern int pthread_barrier_init (pthread_barrier_t *__restrict __barrier, const pthread_barrierattr_t *__restrict __attr, unsigned int __count) ;
extern int pthread_barrier_destroy (pthread_barrier_t *__barrier) ;
extern int pthread_barrier_wait (pthread_barrier_t *__barrier) ;
extern int pthread_barrierattr_init (pthread_barrierattr_t *__attr) ;
extern int pthread_barrierattr_destroy (pthread_barrierattr_t *__attr) ;
extern int pthread_barrierattr_getpshared (const pthread_barrierattr_t * __restrict __attr, int *__restrict __pshared) ;
extern int pthread_barrierattr_setpshared (pthread_barrierattr_t *__attr, int __pshared) ;
extern int pthread_key_create (pthread_key_t *__key, void (*__destr_function) (void *)) ;
extern int pthread_key_delete (pthread_key_t __key) ;
extern void *pthread_getspecific (pthread_key_t __key) ;
extern int pthread_setspecific (pthread_key_t __key, const void *__pointer) ;
extern int pthread_getcpuclockid (pthread_t __thread_id, __clockid_t *__clock_id) ;
extern int pthread_atfork (void (*__prepare) (void), void (*__parent) (void), void (*__child) (void)) ;
