extern int pthread_create (pthread_t *restrict newthread, const pthread_attr_t *restrict attr, void *(*start_routine) (void *), void *restrict arg);
extern void pthread_exit (void *retval);
extern int pthread_join (pthread_t th, void **thread_return);
extern int pthread_detach (pthread_t th);
extern pthread_t pthread_self (void);
extern int pthread_equal (pthread_t thread1, pthread_t thread2);
extern int pthread_attr_init (pthread_attr_t *attr);
extern int pthread_attr_destroy (pthread_attr_t *attr);
extern int pthread_attr_getdetachstate (const pthread_attr_t *attr, int *detachstate);
extern int pthread_attr_setdetachstate (pthread_attr_t *attr, int detachstate);
extern int pthread_attr_getguardsize (const pthread_attr_t *attr, size_t *guardsize);
extern int pthread_attr_setguardsize (pthread_attr_t *attr, size_t guardsize);
extern int pthread_attr_getschedparam (const pthread_attr_t *restrict attr, struct sched_param *restrict param);
extern int pthread_attr_setschedparam (pthread_attr_t *restrict attr, const struct sched_param *restrict param);
extern int pthread_attr_getschedpolicy (const pthread_attr_t *restrict attr, int *restrict policy);
extern int pthread_attr_setschedpolicy (pthread_attr_t *attr, int policy);
extern int pthread_attr_getinheritsched (const pthread_attr_t *restrict attr, int *restrict inherit);
extern int pthread_attr_setinheritsched (pthread_attr_t *attr, int inherit);
extern int pthread_attr_getscope (const pthread_attr_t *restrict attr, int *restrict scope);
extern int pthread_attr_setscope (pthread_attr_t *attr, int scope);
extern int pthread_attr_getstackaddr (const pthread_attr_t *restrict attr, void **restrict stackaddr);
extern int pthread_attr_setstackaddr (pthread_attr_t *attr, void *stackaddr);
extern int pthread_attr_getstacksize (const pthread_attr_t *restrict attr, size_t *restrict stacksize);
extern int pthread_attr_setstacksize (pthread_attr_t *attr, size_t stacksize);
extern int pthread_attr_getstack (const pthread_attr_t *restrict attr, void **restrict stackaddr, size_t *restrict stacksize);
extern int pthread_attr_setstack (pthread_attr_t *attr, void *stackaddr, size_t stacksize);
extern int pthread_setschedparam (pthread_t target_thread, int policy, const struct sched_param *param);
extern int pthread_getschedparam (pthread_t target_thread, int *restrict policy, struct sched_param *restrict param);
extern int pthread_setschedprio (pthread_t target_thread, int prio);
extern int pthread_once (pthread_once_t *once_control, void (*init_routine) (void));
extern int pthread_setcancelstate (int state, int *oldstate);
extern int pthread_setcanceltype (int type, int *oldtype);
extern int pthread_cancel (pthread_t th);
extern void pthread_testcancel (void);
extern void pthread_register_cancel (pthread_unwind_buf_t *buf);
extern void pthread_unregister_cancel (pthread_unwind_buf_t *buf);
extern void pthread_unwind_next (pthread_unwind_buf_t *buf);
extern int sigsetjmp (struct jmp_buf_tag *env, int savemask);
extern int pthread_mutex_init (pthread_mutex_t *mutex, const pthread_mutexattr_t *mutexattr);
extern int pthread_mutex_destroy (pthread_mutex_t *mutex);
extern int pthread_mutex_trylock (pthread_mutex_t *mutex);
extern int pthread_mutex_lock (pthread_mutex_t *mutex);
extern int pthread_mutex_timedlock (pthread_mutex_t *restrict mutex, const struct timespec *restrict abstime);
extern int pthread_mutex_unlock (pthread_mutex_t *mutex);
extern int pthread_mutex_getprioceiling (const pthread_mutex_t * restrict mutex, int *restrict prioceiling);
extern int pthread_mutex_setprioceiling (pthread_mutex_t *restrict mutex, int prioceiling, int *restrict old_ceiling);
extern int pthread_mutex_consistent (pthread_mutex_t *mutex);
extern int pthread_mutexattr_init (pthread_mutexattr_t *attr);
extern int pthread_mutexattr_destroy (pthread_mutexattr_t *attr);
extern int pthread_mutexattr_getpshared (const pthread_mutexattr_t * restrict attr, int *restrict pshared);
extern int pthread_mutexattr_setpshared (pthread_mutexattr_t *attr, int pshared);
extern int pthread_mutexattr_gettype (const pthread_mutexattr_t *restrict attr, int *restrict kind);
extern int pthread_mutexattr_settype (pthread_mutexattr_t *attr, int kind);
extern int pthread_mutexattr_getprotocol (const pthread_mutexattr_t * restrict attr, int *restrict protocol);
extern int pthread_mutexattr_setprotocol (pthread_mutexattr_t *attr, int protocol);
extern int pthread_mutexattr_getprioceiling (const pthread_mutexattr_t * restrict attr, int *restrict prioceiling);
extern int pthread_mutexattr_setprioceiling (pthread_mutexattr_t *attr, int prioceiling);
extern int pthread_mutexattr_getrobust (const pthread_mutexattr_t *attr, int *robustness);
extern int pthread_mutexattr_setrobust (pthread_mutexattr_t *attr, int robustness);
extern int pthread_rwlock_init (pthread_rwlock_t *restrict rwlock, const pthread_rwlockattr_t *restrict attr);
extern int pthread_rwlock_destroy (pthread_rwlock_t *rwlock);
extern int pthread_rwlock_rdlock (pthread_rwlock_t *rwlock);
extern int pthread_rwlock_tryrdlock (pthread_rwlock_t *rwlock);
extern int pthread_rwlock_timedrdlock (pthread_rwlock_t *restrict rwlock, const struct timespec *restrict abstime);
extern int pthread_rwlock_wrlock (pthread_rwlock_t *rwlock);
extern int pthread_rwlock_trywrlock (pthread_rwlock_t *rwlock);
extern int pthread_rwlock_timedwrlock (pthread_rwlock_t *restrict rwlock, const struct timespec *restrict abstime);
extern int pthread_rwlock_unlock (pthread_rwlock_t *rwlock);
extern int pthread_rwlockattr_init (pthread_rwlockattr_t *attr);
extern int pthread_rwlockattr_destroy (pthread_rwlockattr_t *attr);
extern int pthread_rwlockattr_getpshared (const pthread_rwlockattr_t * restrict attr, int *restrict pshared);
extern int pthread_rwlockattr_setpshared (pthread_rwlockattr_t *attr, int pshared);
extern int pthread_rwlockattr_getkind_np (const pthread_rwlockattr_t * restrict attr, int *restrict pref);
extern int pthread_rwlockattr_setkind_np (pthread_rwlockattr_t *attr, int pref);
extern int pthread_cond_init (pthread_cond_t *restrict cond, const pthread_condattr_t *restrict cond_attr);
extern int pthread_cond_destroy (pthread_cond_t *cond);
extern int pthread_cond_signal (pthread_cond_t *cond);
extern int pthread_cond_broadcast (pthread_cond_t *cond);
extern int pthread_cond_wait (pthread_cond_t *restrict cond, pthread_mutex_t *restrict mutex);
extern int pthread_cond_timedwait (pthread_cond_t *restrict cond, pthread_mutex_t *restrict mutex, const struct timespec *restrict abstime);
extern int pthread_condattr_init (pthread_condattr_t *attr);
extern int pthread_condattr_destroy (pthread_condattr_t *attr);
extern int pthread_condattr_getpshared (const pthread_condattr_t * restrict attr, int *restrict pshared);
extern int pthread_condattr_setpshared (pthread_condattr_t *attr, int pshared);
extern int pthread_condattr_getclock (const pthread_condattr_t * restrict attr, clockid_t *restrict clock_id);
extern int pthread_condattr_setclock (pthread_condattr_t *attr, clockid_t clock_id);
extern int pthread_spin_init (pthread_spinlock_t *lock, int pshared);
extern int pthread_spin_destroy (pthread_spinlock_t *lock);
extern int pthread_spin_lock (pthread_spinlock_t *lock);
extern int pthread_spin_trylock (pthread_spinlock_t *lock);
extern int pthread_spin_unlock (pthread_spinlock_t *lock);
extern int pthread_barrier_init (pthread_barrier_t *restrict barrier, const pthread_barrierattr_t *restrict attr, unsigned int count);
extern int pthread_barrier_destroy (pthread_barrier_t *barrier);
extern int pthread_barrier_wait (pthread_barrier_t *barrier);
extern int pthread_barrierattr_init (pthread_barrierattr_t *attr);
extern int pthread_barrierattr_destroy (pthread_barrierattr_t *attr);
extern int pthread_barrierattr_getpshared (const pthread_barrierattr_t * restrict attr, int *restrict pshared);
extern int pthread_barrierattr_setpshared (pthread_barrierattr_t *attr, int pshared);
extern int pthread_key_create (pthread_key_t *key, void (*destr_function) (void *));
extern int pthread_key_delete (pthread_key_t key);
extern void *pthread_getspecific (pthread_key_t key);
extern int pthread_setspecific (pthread_key_t key, const void *pointer);
extern int pthread_getcpuclockid (pthread_t thread_id, clockid_t *clock_id);
extern int pthread_atfork (void (*prepare) (void), void (*parent) (void), void (*child) (void));
